- improved script for mounting skynet stuff

diff --git a/bin/skynet_mount b/bin/skynet_mount
--- a/bin/skynet_mount
+++ b/bin/skynet_mount
@@ -2,14 +2,26 @@
 
 # Mount NAS via SSH
 
-ping -c 1 -w 3 skynet
-RETVAL=$?
-if [ "$RETVAL" == 0 ] 
+if [ ! "$(ls -A /home/schellsn/mnt/nas/musik)" ]
 then
-    sshfs -o uid=1000,gid=1000 -C -p 443 stefan@skynet:/media/nas/bilder /home/schellsn/mnt/nas/bilder
-    sshfs -o uid=1000,gid=1000 -C -p 443 stefan@skynet:/media/nas/videos /home/schellsn/mnt/nas/videos
-    sshfs -o uid=1000,gid=1000 -C -p 443 stefan@skynet:/media/nas/musik /home/schellsn/mnt/nas/musik
-    sshfs -o uid=1000,gid=1000 -C -p 443 stefan@skynet:/media/nas/etc /home/schellsn/mnt/nas/etc
-    sshfs -o uid=1000,gid=1000 -C -p 443 stefan@skynet:/media/nas/backup/stefan /home/schellsn/mnt/nas/backup
+    ping -c 1 -w 3 5.158.134.10 &> /dev/null
+    RETVAL=$?
+    if [ "$RETVAL" == 0 ] 
+    then
+        sshfs -o uid=1000,gid=1000 -C -p 443 stefan@5.158.134.10:/media/nas/bilder /home/schellsn/mnt/nas/bilder &> /dev/null
+        sshfs -o uid=1000,gid=1000 -C -p 443 stefan@5.158.134.10:/media/nas/videos /home/schellsn/mnt/nas/videos &> /dev/null
+        sshfs -o uid=1000,gid=1000 -C -p 443 stefan@5.158.134.10:/media/nas/musik /home/schellsn/mnt/nas/musik &> /dev/null
+        sshfs -o uid=1000,gid=1000 -C -p 443 stefan@5.158.134.10:/media/nas/etc /home/schellsn/mnt/nas/etc &> /dev/null
+        sshfs -o uid=1000,gid=1000 -C -p 443 stefan@5.158.134.10:/media/nas/backup/stefan /home/schellsn/mnt/nas/backup &> /dev/null
+        RETVAL=$?
+        if [ "$RETVAL" == 0 ] 
+        then
+            echo "mounted skynet drives..."
+        else
+            echo "could not mount skynet drives..."
+        fi
+    fi
+else
+    echo "skynet drives are mounted..."
 fi
 
